# Sử dụng hình ảnh Node.js chính thức từ Docker Hub
FROM node:18-alpine

# Thiết lập thư mục làm việc trong container
WORKDIR /src

# Sao chép file package.json và package-lock.json (nếu có) vào container
COPY package*.json ./

# Cài đặt các dependencies
RUN npm install

# Sao chép toàn bộ mã nguồn vào thư mục làm việc
COPY . .

# Expose port mà ứng dụng Node.js chạy (thường là 3000)
EXPOSE 8080

# Lệnh chạy ứng dụng khi container khởi động
CMD ["npm", "start"]